<?php
require __DIR__.'/../includes/bootstrap.php'; require_coach_or_admin('overview'); require __DIR__.'/../includes/layout.php';
$to=valid_date(scalar($_GET,'to',date('Y-m-d')));$from=valid_date(scalar($_GET,'from',(new DateTimeImmutable($to))->modify('-83 days')->format('Y-m-d')));
if($from>$to || (new DateTimeImmutable($from))->diff(new DateTimeImmutable($to))->days>366) throw new InvalidArgumentException('Kies een periode van maximaal 366 dagen.');
$days=query('SELECT * FROM effective_daily_metrics WHERE date BETWEEN ? AND ? ORDER BY date DESC',[$from,$to])->fetchAll();
$weeks=query('SELECT * FROM weekly_checkins WHERE week_start BETWEEN ? AND ? ORDER BY week_start DESC',[monday($from),monday($to)])->fetchAll();
$workouts=query('SELECT id,date,workout_name,duration_minutes,total_volume FROM workouts WHERE date BETWEEN ? AND ? ORDER BY date DESC,id DESC',[$from,$to])->fetchAll();
$hcRows=query('SELECT * FROM health_connect_daily WHERE date BETWEEN ? AND ? ORDER BY date DESC',[$from,$to])->fetchAll();
$sets=query('SELECT s.* FROM workout_sets s JOIN workouts w ON w.id=s.workout_id WHERE w.date BETWEEN ? AND ? ORDER BY s.exercise_index,s.set_index',[$from,$to])->fetchAll();
$byWorkout=[]; $byDay=[]; foreach($sets as $s) $byWorkout[$s['workout_id']][]=$s;
foreach($workouts as $w) $byDay[$w['date']][]=$w['workout_name'];
$dayRows=array_column($days,null,'date');foreach($byDay as $date=>$names) if(!isset($dayRows[$date])) $dayRows[$date]=['date'=>$date];krsort($dayRows);
page_start('Ruwe data'); ?>
<p class="eyebrow">ALLE DETAILS</p><h1>Jouw gegevens.</h1><p><a href="<?=e(url('coach.php'))?>">← Terug naar het overzicht</a></p>
<form method="get" class="card range"><label>Van<input type="date" name="from" value="<?=e($from)?>" required min="2000-01-01" max="<?=date('Y-m-d')?>"></label><label>Tot en met<input type="date" name="to" value="<?=e($to)?>" required min="2000-01-01" max="<?=date('Y-m-d')?>"></label><button class="primary">Periode tonen</button></form>
<section class="card"><h2>Dagelijkse metingen</h2><div class="table-wrap"><table><thead><tr><?php foreach(['Datum','Gewicht (kg)','Stappen','Tijd in bed','Kwaliteit','Rusthartslag','Bloeddruk','Navel (cm)','Heup (cm)','Hevy-training','Slaapregistratie HC','Bron gewicht / stappen'] as $h): ?><th><?=e($h)?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($dayRows as $d): ?><tr><td><?=e($d['date'])?></td><td><?=display_number($d['weight']??null)?></td><td><?=display_number($d['steps']??null,0)?></td><td><?=sleep_label($d['sleep_minutes']??null)?></td><td><?=display_number($d['sleep_quality']??null,0)?></td><td><?=display_number($d['resting_hr']??null,0)?></td><td><?=isset($d['blood_pressure_sys'])?e($d['blood_pressure_sys'].' / '.$d['blood_pressure_dia']):'—'?></td><td><?=display_number($d['navel_cm']??null)?></td><td><?=display_number($d['hip_cm']??null)?></td><td><?=e(implode(', ',$byDay[$d['date']]??[]))?></td><td><?=sleep_label($d['hc_sleep_minutes']??null)?></td><td><?=e(($d['weight_source']??'—').' / '.($d['steps_source']??'—'))?></td></tr><?php endforeach; ?><?php if(!$dayRows): ?><tr><td colspan="12">Geen metingen of trainingen in deze periode.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="card"><h2>Weekchecks</h2><?php if(!$weeks): ?><p>Geen weekchecks in deze periode.</p><?php endif; ?><?php foreach($weeks as $w): ?><details><summary>Week van <?=e($w['week_start'])?></summary><dl><?php foreach(['libido'=>'Libido (1–5)','cravings'=>'Cravings (1 = veel, 5 = geen)' ,'stress'=>'Stress (1–5)','libido_details'=>'Libido — toelichting','stress_details'=>'Stress — toelichting','bowel_movement'=>'Ontlasting'] as $k=>$label): ?><dt><?=e($label)?></dt><dd><?=nl2br(e($w[$k]??'—'))?></dd><?php endforeach; ?></dl></details><?php endforeach; ?></section>
<section class="card"><h2>Trainingen & sets</h2><?php if(!$workouts): ?><p>Geen geïmporteerde trainingen in deze periode.</p><?php endif; ?><?php foreach($workouts as $w): ?><details><summary><?=e($w['date'].' · '.$w['workout_name'])?> · <?=display_number($w['duration_minutes'],0)?> min · <?=display_number($w['total_volume'],0)?> kg</summary><div class="table-wrap"><table><thead><tr><th>Oefening</th><th>Set</th><th>Type</th><th>kg</th><th>Reps</th><th>Meter</th><th>Seconden</th><th>RPE</th></tr></thead><tbody><?php foreach($byWorkout[$w['id']]??[] as $s): ?><tr><td><?=e($s['exercise_name'])?></td><td><?=(int)$s['set_index']+1?></td><td><?=e($s['set_type'])?></td><?php foreach(['weight_kg','reps','distance','duration_seconds','rpe'] as $k): ?><td><?=display_number($s[$k],$k==='reps'?0:1)?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details><?php endforeach; ?></section>
<section class="card"><h2>Health Connect · oorspronkelijke import</h2><p class="muted">Deze bronwaarden blijven ook zichtbaar als handmatige invoer voorrang heeft. Slaap is geaggregeerde sessieduur per kalenderdag; een nacht kan over twee dagen verdeeld zijn. Bronapps bij stappen/slaap zijn de gezamenlijke bronnen van die dagaggregatie.</p><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Stappen</th><th>Gewicht</th><th>Slaapregistratie</th><th>Bronnen en bijgewerkt (UTC)</th></tr></thead><tbody><?php foreach($hcRows as $hc):?><tr><td><?=e($hc['date'])?></td><td><?=display_number($hc['steps'],0)?></td><td><?=display_number($hc['weight'])?></td><td><?=sleep_label($hc['sleep_minutes'])?></td><td><?php foreach(['steps'=>'Stappen','weight'=>'Gewicht','sleep_minutes'=>'Slaap'] as $key=>$label):?><div><?=e($label.': '.($hc[$key.'_sources']??'—').' · '.($hc[$key.'_synced_at']??'—'))?></div><?php endforeach;?></td></tr><?php endforeach;?><?php if(!$hcRows):?><tr><td colspan="5">Nog geen Health Connect-data in deze periode.</td></tr><?php endif;?></tbody></table></div></section>
<?php page_end();
