<?php
function page_start(string $title): void { ?>
<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=e($title)?> · Ritme</title><link rel="stylesheet" href="<?=e(url('assets/css/app.css'))?>"></head><body>
<header class="top"><a class="brand" href="<?=e(url(admin()?'index.php':coach_home()))?>"><span class="brand-mark">r.</span> ritme<span class="brand-sub">FITNESS CHECK-IN</span></a>
<?php if(admin()): ?><nav aria-label="Hoofdnavigatie"><?php foreach(['index.php'=>'Vandaag','weekly.php'=>'Weekcheck','coach.php'=>'Overzicht','training.php'=>'Training','nutrition.php'=>'Voeding','tokens.php'=>'Delen','devices.php'=>'Telefoon'] as $path=>$label): ?><a <?=basename($_SERVER['SCRIPT_NAME'])===$path?'aria-current="page"':''?> href="<?=e(url($path))?>"><?=e($label)?></a><?php endforeach; ?></nav><form action="<?=e(url('logout.php'))?>" method="post"><?php csrf_field(); ?><button class="quiet">Uitloggen</button></form><?php else: ?><?php $coachNav=[];if(coach_can('overview'))$coachNav['coach.php']='Overzicht';if(coach_can('training'))$coachNav['training.php']='Training';if(coach_can('nutrition'))$coachNav['nutrition.php']='Voeding';if($coachNav):?><nav aria-label="Coachnavigatie"><?php foreach($coachNav as $path=>$label):?><a <?=basename($_SERVER['SCRIPT_NAME'])===$path?'aria-current="page"':''?> href="<?=e(url($path))?>"><?=e($label)?></a><?php endforeach;?></nav><?php endif;?><span class="badge">Coach · alleen lezen</span><?php endif; ?></header><main>
<?php if(isset($_SESSION['flash'])): ?><div class="notice" role="status"><?=e($_SESSION['flash'])?></div><?php unset($_SESSION['flash']); endif;
}
function page_end(): void { echo '</main><footer>Ritme · Kleine stappen, helder overzicht.</footer></body></html>'; }
function scale(string $key,string $label,$value,string $hint='1 = laag · 5 = hoog'): void { ?>
<fieldset class="scale"><legend><?=e($label)?></legend><div class="scale-options"><?php for($i=1;$i<=5;$i++): ?><label><input type="radio" name="<?=e($key)?>" value="<?=$i?>" <?=((string)$value===(string)$i)?'checked':''?>><span><?=$i?></span></label><?php endfor; ?><label><input type="radio" name="<?=e($key)?>" value="" <?=($value===null || $value==='')?'checked':''?>><span>—</span></label></div><small><?=e($hint)?> · — = niet ingevuld</small></fieldset>
<?php }
